wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1697086020.139951
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 2
      - 5
      13: linux-x86_64
task:
  desc: null
  value: none
agent:
  desc: null
  value: ppo_lm
config:
  desc: null
  value: example
prompt:
  desc: null
  value: GPT2
dataset:
  desc: null
  value: example
pretrain_data_path:
  desc: null
  value: ./pretrain_data/ChatGPT.csv
mode:
  desc: null
  value: finetune
exp_name:
  desc: null
  value: tru-test2
save_path:
  desc: null
  value: tru-test2
model_ckpt:
  desc: null
  value: ''
model_name:
  desc: null
  value: /work/u5273929/bias-ppo/gpt2_finetune/gpt2-m/gpt2-m-ChatGPT/checkpoint-2985
ratio:
  desc: null
  value: 4
log_interval:
  desc: null
  value: 5
save_interval:
  desc: null
  value: 10
seed:
  desc: null
  value: 42
bz:
  desc: null
  value: 2
k_epoch:
  desc: null
  value: 3
discount_r:
  desc: null
  value: 1.0
end_step:
  desc: null
  value: 60
sample_time:
  desc: null
  value: 1
inner_lr:
  desc: null
  value: 9.0e-06
outer_lr:
  desc: null
  value: 1.0e-05
max_pt_len:
  desc: null
  value: 30
mse_lr:
  desc: null
  value: 1
ep_lr:
  desc: null
  value: 1.0
eps_clip:
  desc: null
  value: 0.2
coh_r:
  desc: null
  value: 0.01
lm_lr:
  desc: null
  value: 0.1
num_testing:
  desc: null
  value: 1
update_demo:
  desc: null
  value: true
init_step:
  desc: null
  value: '0'
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 0.9
wandb:
  desc: null
  value: online
bot:
  desc: null
  value: hf-causal-experimental
bot_args:
  desc: null
  value: pretrained=meta-llama/Llama-2-7b-chat-hf,use_accelerate=True
tasks:
  desc: null
  value: truthful_qa
provide_description:
  desc: null
  value: false
num_fewshot:
  desc: null
  value: 0
limit:
  desc: null
  value: 40.0
data_sampling:
  desc: null
  value: null
no_cache:
  desc: null
  value: true
check_integrity:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
